### ISSUE TITLE
Testing Signature Transformations

### ISSUE THREAD

**Issue by jozefg** [JonPRL/sml-red-jonprl#13]
Once #12 lands, we'll have a nice way to test all the signature elaboration stuff. It would probably be good to add

 1. A validator for each signature transformation or at least the last one
 2. A few examples of signatures to be parsed an elaborated
 3. Testing glue to make this all run
 4. Add this to the travis build cycle

That way we don't have a bunch of code in there that's never been really run or tested :)

**Comment by jonsterling** [comment]
That'd be awesome, yes!! As the parser stuff starts rolling in, we can also add some sanity tests for it as well.

Is there a lightweight way to test SML code that you have in mind? I guess one thing that's kind of nice about SML is that you can run effects at link-time, so we could just have a `.mlb` file that included test structures.

**Comment by jozefg** [comment]
@jonsterling That's basically what I had in mind. Just a file with a bunch of

    val () = runTestOrRaiseExn ()

sort of stuff and perhaps some printing for debugging output. Pretty? Not at all, but it will do until I get around to writing my unit testing framework for SML

**Comment by jonsterling** [comment]
@jozefg :+1: sounds perfect!

**Comment by ak3n** [comment]
Are you sure that there are link-time effects? I can't evaluate `val () = print "hello"` while executing `mlton test.mlb`.

test.mlb
```sml
local
  $(SML_LIB)/basis/basis.mlb
  ../lib/cmlib/cmlib.mlb

  test_signature_parser.sml
in
  structure TestSignatureParser
end
```
test_signature_parser.sml
```sml
structure TestSignatureParser =
struct
  val () = print "hello"
end

val () = print "hello2"
```

```
➜  mlton tests/test.mlb 
➜  ./tests/test 
hellohello2%
```

**Comment by jonsterling** [comment]
@ak3n Oh, that is strange! Perhaps this is just behavior I was used to with SML/NJ? Could you try throwing an exception instead of printing just to be absolutely sure?

**Comment by jonsterling** [comment]
I suppose it is no big deal in any case, since we can just run the executable generated by MLton if we have to.

**Comment by MatthewFluet** [comment]
Right, MLton does no link-time evaluation.  Nor does SML/NJ.  The terminology might be misleading and/or inappropriate for MLton and SML/NJ, neither of which precisely fit the .c -compile-> .o -link-> a.out flow.

Really, the difference is that SML/NJ does "compile-time" evaluation.  Given your `TestSignatureParser` above, if it were included in a `test-signature-parser.cm` file, then the effects would occur when that CM group was compiled, but would not occur again when compiling another `sources.cm` file that referenced `test-signature-parser.cm`; nor would it occur when running a heap image with an exported `val main : string * string list -> OS.Process.status` that (transitively) references `test-signature-parser.cm`.  On the other hand, if `TestSignatureParser` were included in a `test-signature-parser.mlb` file, then the effects would occur whenever *any* program that (transitively) included `test-signature-parser.mlb` was executed.

For top-level effects, like tests, the usage isn't that different, since one is usually only interested in running the tests once per compile; subsequent runs of the tests would occur when some (transitive) dependency has changed and a re-compile is required.  When you want to check the tests under SML/NJ, just compile `test.cm`.  When you want to check the tests under MLton, just compile and run `test.mlb`.  Where it is more meaningfully different is something like:
```sml
structure Primes =
struct
  val primes : int list = (* ... compute primes ... *)
end
```
SML/NJ will compute primes once when that module is compiled, while MLton will recompute primes each time a program that uses that module is executed.  The other place where it can meaningfully different is something like:
```sml
structure Template =
struct
  val template : string = let val ins = TextIO.openIn "template" in TextIO.inputAll ins before TextIO.closeIn ins end
end
```
SML/NJ will read the `template` once when that module is compiled, while MLton will (attempt) to read the `template` each time a program that uses the that module is executed.  This can be problematic if the `template` file doesn't exist or is not in the same relative location when the MLton compiled programs are executed.

In any case, the best approach for tests is as @jonsterling suggests: for each test, compile the corresponding `test.mlb` file and then run the resulting executable.  Or, just create a master `test.mlb` that includes each of the individual `test-component.mlb`s.

**Comment by jonsterling** [comment]
@MatthewFluet Wow, thank you so much for the very detailed overview of what's going on! I think we'll follow your advice then, and have our script compile `test.mlb` and run the resulting executable.
